### ISSUE TITLE
how can i build this

### ISSUE THREAD

**Issue by leapofazzam123** [Progressbar-Discord-Server/PrimaryIncidentRPG#4]
im in linux

**Comment by zai-tm** [comment]
you have to buy Ubuntu dlc on steam
yes, this is a serious answer

**Comment by RealMCoded** [comment]
GameMaker's official guide can be found [here](https://help.yoyogames.com/hc/en-us/articles/235186168-Setting-Up-For-Ubuntu), please note that you must at least be a subscriber of the CREATOR tier to access Ubuntu export.
